[package]
name = "mailtutan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-smtp-server = "0.1.1"
anyhow = "1.0"
tokio = "1.26"
async-trait = "0.1.67"
axum = "0.6.18"
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
