[package]
name = "mailtutan"
version = "0.1.0"
edition = "2021"

[lib]
name = "mailtutan"
path = "src/lib.rs"

[[bin]]
name = "mailtutan"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-smtp-server = "0.1.1"
anyhow = "1.0"
tokio = "1.26"
async-trait = "0.1.67"
axum = { version =  "0.6.18", features = ["ws"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
lazy_static = "1.4.0"
mailparse = "0.14.0"
mailin-embedded = "0.8.0"
chrono = "0.4.24"
futures = "0.3.28"

[profile.release]
opt-level = 'z'
lto = true
strip = true
