# [package]
# name = "mailtutan"
# authors = ["Mohsen Alizadeh <mohsen@alizadeh.us>"]
# homepage= "https://github.com/mohsen-alizadeh/mailtutan"
# version = "0.1.0"
# edition = "2021"


[workspace]
members = [
  "mailtutan",
  "mailtutan-lib",
  "mailtutan-web"
]
